# Generated by Django 3.2.12 on 2022-07-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='times_followed',
        ),
    ]
