# Generated by Django 3.2.12 on 2022-07-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0006_shortener'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shortener',
        ),
    ]
